export * from "./Health";
export * from "./Home";
export * from "./Partners";
export * from "./Staff";
export * from "./Contact";
export * from "./Transparency";
export * from "./Donations";
export * from "./Gallery";
export * from "./Activities";
export * from './admin/Staff'
